
name: Dev Deploy

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install backend dependencies
      run: |
        cd app/backend
        pip install -r requirements.txt

    - name: Run backend unit tests
      run: echo "No tests yet"

    - name: Docker Build and Push (Dev)
      run: echo "Build and push dev container here"
